### ISSUE TITLE
What happened on Dec 9, 2016

### ISSUE THREAD

**Issue by salvador-dali** [ornicar/lichess-db#10]
There are a few strangely evaluated games:

 - https://lichess.org/Kciy5Svq
 - https://lichess.org/ArABRXKI
 - https://lichess.org/IWR0M3NF

where each position is mate in 5. All such games happened on Dec 9 2016. Probably there are more games like these. Why has this happened?

**Comment by ornicar** [comment]
A temporary bug, obviously.

**Comment by salvador-dali** [comment]
I can see by myself that this is a bug. The question was why has this happened as normally stockfish does not give such evaluations. A good answer might also tell whether:
 - this bug affects only the games I linked or other games are affected as well
 - anything will be done for these games or they will be left as is

If you do not care about these bugs, I can understand it.

**Comment by ornicar** [comment]
The bug was on lichess side interpreting or storing evaluations.
