### ISSUE TITLE
More information about "Before 2015: Some games with illegal moves were recorded. "

### ISSUE THREAD

**Issue by Sopel97** [ornicar/lichess-db#23]
There is exactly 7 such games. Ranging from 2014 to 2016
https://lichess.org/0ouSssGU
https://lichess.org/wBhVZYgI
https://lichess.org/g2HCpy8B
https://lichess.org/gI2EuG6T
https://lichess.org/w2WvLGHQ
https://lichess.org/XDQeUk6j
https://lichess.org/G7KuUEum
All illegal moves were castling moves.

It might be worth to document this because people using the files may not notice at first.

**Comment by Keisial** [comment]
Please note that the board on the above links do not show the invalid castling, a truncated list is silently presented (view the PGN for the whole list of moves).
