### ISSUE TITLE
"Opening" tag sometimes inconsistent with opening explorer

### ISSUE THREAD

**Issue by malcolmsharpe** [ornicar/lichess-db#26]
Sometimes the "opening" tag in the database PGN specifies a different opening than what the opening explorer shows. In these cases, the opening explorer has been correct in the examples I have checked.

For example, consider this game:
https://lichess.org/kOmHdNie

In the opening explorer, it is correctly classified as "Bongcloud Attack" from move 2 onward. In the database file `lichess_db_standard_rated_2020-09.pgn.bz2`, though, the PGN appears as follows, with the tag `[Opening "King's Pawn Game"]`:

```
[Event "Rated Blitz game"]
[Site "https://lichess.org/kOmHdNie"]
[Date "2020.09.01"]
[Round "-"]
[White "Vexation"]
[Black "Rica_Miorelli"]
[Result "1-0"]
[UTCDate "2020.09.01"]
[UTCTime "01:06:50"]
[WhiteElo "1286"]
[BlackElo "1260"]
[WhiteRatingDiff "+5"]
[BlackRatingDiff "-5"]
[ECO "C20"]
[Opening "King's Pawn Game"]
[TimeControl "180+0"]
[Termination "Time forfeit"]

1. e4 { [%clk 0:03:00] } e5 { [%clk 0:03:00] } 2. Ke2 { [%clk 0:02:59] } Nf6 { [%clk 0:02:58] } 3. f3 { [%clk 0:02:58] } d6 { [%clk 0:02:56] } 4. d3 { [%clk 0:02:57] } Be7 { [%clk 0:02:55] } 5. Nh3 { [%clk 0:02:53] } O-O { [%clk 0:02:53] } 6. c3 { [%clk 0:02:50] } Nc6 { [%clk 0:02:52] } 7. Nd2 { [%clk 0:02:47] } d5 { [%clk 0:02:45] } 8. b3 { [%clk 0:02:43] } dxe4 { [%clk 0:02:43] } 9. dxe4 { [%clk 0:02:40] } a6 { [%clk 0:02:37] } 10. Nc4 { [%clk 0:02:37] } b5 { [%clk 0:02:34] } 11. Qxd8 { [%clk 0:02:34] } Rxd8 { [%clk 0:02:32] } 12. Ne3 { [%clk 0:02:29] } b4 { [%clk 0:02:26] } 13. c4 { [%clk 0:02:26] } a5 { [%clk 0:02:21] } 14. Nf5 { [%clk 0:02:13] } Nd4+ { [%clk 0:02:18] } 15. Nxd4 { [%clk 0:02:11] } exd4 { [%clk 0:02:15] } 16. Kd3 { [%clk 0:02:08] } c5 { [%clk 0:02:11] } 17. Bg5 { [%clk 0:02:03] } Bxh3 { [%clk 0:02:09] } 18. gxh3 { [%clk 0:02:02] } h6 { [%clk 0:02:07] } 19. Bxf6 { [%clk 0:01:59] } Bxf6 { [%clk 0:02:06] } 20. h4 { [%clk 0:01:58] } a4 { [%clk 0:01:56] } 21. bxa4 { [%clk 0:01:54] } Rxa4 { [%clk 0:01:54] } 22. Rg1 { [%clk 0:01:51] } b3 { [%clk 0:01:53] } 23. a3 { [%clk 0:01:48] } b2 { [%clk 0:01:50] } 24. Rb1 { [%clk 0:01:44] } Rb8 { [%clk 0:01:47] } 25. Kc2 { [%clk 0:01:41] } Rxc4+ { [%clk 0:01:39] } 26. Kd3 { [%clk 0:01:37] } Ra4 { [%clk 0:01:37] } 27. Bh3 { [%clk 0:01:33] } Rxa3+ { [%clk 0:01:34] } 28. Kc4 { [%clk 0:01:31] } Rc3+ { [%clk 0:01:27] } 29. Kd5 { [%clk 0:01:27] } Rd8+ { [%clk 0:01:21] } 30. Kc6 { [%clk 0:01:24] } Be7 { [%clk 0:01:14] } 31. Bd7 { [%clk 0:01:18] } Rxf3 { [%clk 0:01:01] } 32. Rxb2 { [%clk 0:01:16] } Rf6+ { [%clk 0:00:59] } 33. Kc7 { [%clk 0:01:14] } Ra6 { [%clk 0:00:52] } 34. Rb8 { [%clk 0:01:09] } Rxb8 { [%clk 0:00:48] } 35. Kxb8 { [%clk 0:01:07] } Bd6+ { [%clk 0:00:46] } 36. Kb7 { [%clk 0:01:06] } Ra4 { [%clk 0:00:39] } 37. Bxa4 { [%clk 0:01:05] } d3 { [%clk 0:00:34] } 38. Rd1 { [%clk 0:01:02] } c4 { [%clk 0:00:33] } 39. Kc6 { [%clk 0:01:00] } Bxh2 { [%clk 0:00:31] } 40. Bb5 { [%clk 0:00:57] } c3 { [%clk 0:00:23] } 41. Bxd3 { [%clk 0:00:55] } Bf4 { [%clk 0:00:22] } 42. Rf1 { [%clk 0:00:51] } 1-0
```

This game ought to be classified as "Bongcloud Attack" in the database.

In fact, "Bongcloud Attack" does not appear as an opening even once in the file. There seem to be other openings affected by this too. For example, "Fried Fox Defense" seems consistently misclassified as "Barnes Defense" in the database.

**Comment by niklasf** [comment]
The opening name database is part of https://github.com/ornicar/scalachess. Improvements are not applied retroactively to already exported files. The next export should have all recent updates (via #27).

**Comment by malcolmsharpe** [comment]
Thanks, but is it the case that "Bongcloud Attack" was not present in the version of scalachess used for database export? It seems to me that it was present (but I may be misunderstanding).

If I understand the [the pull request](https://github.com/ornicar/lichess-db/pull/27/commits/7d14667153cc764f0e245c2a01a4f4363921259d) correctly, the previous version of scalachess used was 9.2.1, from 2020-01-29. That corresponds to [commit 0a7d6f2c63b1ca06cd3c958ed3264e738af5c5f6](https://github.com/ornicar/scalachess/commit/0a7d6f2c63b1ca06cd3c958ed3264e738af5c5f6). But as of that commit, ["Bongcloud Attack" was present in FullOpeningPart1.scala](https://github.com/ornicar/scalachess/blob/0a7d6f2c63b1ca06cd3c958ed3264e738af5c5f6/src/main/scala/opening/FullOpeningPart1.scala).

"Bongcloud Attack" seems to have been added to scalachess by [commit 3901aba54851ac26477a480aa45409d5f359d7f0](https://github.com/ornicar/scalachess/commit/3901aba54851ac26477a480aa45409d5f359d7f0), on 2018-06-20, which [became 8.6.12 on 2018-07-05](https://github.com/ornicar/scalachess/commit/4d5783264e0c5736746a876d10ac0e991af570ba#diff-5634c415cd8c8504fdb973a3ed092300b43c4b8fc1e184f7249eb29a55511f91).

It seems that lichess-db was updated to use post-8.6.12 scalachess [by commit ed9cf380cf876cf8f18c6985b009ed0288fe5b78 on 2020-02-01](https://github.com/ornicar/lichess-db/commit/ed9cf380cf876cf8f18c6985b009ed0288fe5b78). So shouldn't the database export for 2020-09 already have been "Bongcloud Attack"-aware? To speculate, could the database export be running an out-of-date version of lichess-db?

**Comment by niklasf** [comment]
Good analysis.

> To speculate, could the database export be running an out-of-date version of lichess-db?

On the server it's up to date with the latest "Related projects", but hard to tell if that was before or after the last export. I guess we'll learn next month if it was that or another issue.

**Comment by niklasf** [comment]
This appears to be correct in the 2020-12 export, so I guess it's not worth figuring out what exactly went wrong historocially.

Due to #31 we may eventually re-export older games. They would get better opening tags, too, then.
