### ISSUE TITLE
Handling multiple answers

### ISSUE THREAD

**Issue by pnxdxt** [ornicar/lichess-db#41]
Hi guys!

I am building a quick puzzle trainer for fun. [github.com/chesspecker](https://github.com/chesspecker)

How does Lichess puzzles handles multiple answers for examples multiple mate in one?

Here is an example:

`{
PuzzleId: "GKhUo",
FEN: "r5k1/p4pp1/7p/2p5/NpP1PB2/1B3pq1/PP4bb/R4Q1K w - - 6 28",
Moves: "f1g2 f3g2",
Rating: 1860,
RatingDeviation: 257,
Popularity: -100,
NbPlays: 7,
Themes: Array,
GameUrl : "https://lichess.org/xuPt7fwP#55",
}`

https://lichess.org/training/GKhUo

**Comment by kraktus** [comment]
It's checked client-side I think

**Comment by pnxdxt** [comment]
I think so too but I was wondering how since Moves only contains one solution.

**Comment by pnxdxt** [comment]
I found a quick way via this commit https://github.com/chesspecker/frontend/commit/2017a6de643c3fd0591c8e8b23bce6330193b486

But it only works if a puzzle with multiple solutions can only be mate in 1 solutions.
I guess it's the case but not sure?

**Comment by kraktus** [comment]
It is the case 👍

**Comment by pnxdxt** [comment]
Okay thanks a lot, closing this issue.
