### ISSUE TITLE
ECO and opening in puzzles

### ISSUE THREAD

**Issue by lukasmonk** [ornicar/lichess-db#43]
Two fields that could provide useful information to the puzzles would be ECO and opening.
Although my interest is in a sense selfish (it would save me the time of downloading the games), I think it might be of interest to more people. 
I got the idea from: [Scott blog: Lichess puzzles, by ECO](https://cshancock.netlify.app/post/2021-06-23-lichess-puzzles-by-eco/)

**Comment by xb8** [comment]
i do need to download games given a certain set of moves aswell, either by pgn or fen or name of the opening would be fine. Is there not a way to do so?

**Comment by lukasmonk** [comment]
I was referring to the puzzles database, and it's already included, I forgot about this issue, so I'm closing it.
